######################################################################
# Automatically generated by qmake (3.0) ?? ?? 9 16:30:48 2018
######################################################################



TEMPLATE = app
TARGET = QtRequester

QT += core network xml
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
CONFIG += debug_and_release

# C++17 is required (e.g. inline static members in thememanager.h).
# qmake only understands CONFIG += c++17 since Qt 5.12; older toolchains
# need the compiler flag passed directly.
greaterThan(QT_MAJOR_VERSION, 5) {
    # Qt 6: C++17 is the baseline.
    CONFIG += c++17
} else: greaterThan(QT_MINOR_VERSION, 11) {
    # Qt 5.12 – 5.15.
    CONFIG += c++17
} else {
    # Qt 5.6 – 5.11: qmake has no c++17 CONFIG value.
    msvc: QMAKE_CXXFLAGS += /std:c++17
    else: QMAKE_CXXFLAGS += -std=c++17
}

INCLUDEPATH += . \
                $$PWD/../../include \
                $$PWD/resources

# Input
HEADERS += networkrequesttool.h \
           jsonsyntaxhighlighter.h \
           xmlsyntaxhighlighter.h \
           thememanager.h
FORMS += NetworkRequestTool.ui 
SOURCES += main.cpp networkrequesttool.cpp \
           jsonsyntaxhighlighter.cpp \
           xmlsyntaxhighlighter.cpp

greaterThan(QT_MAJOR_VERSION, 4) {
    TARGET_ARCH=$${QT_ARCH}
} else {
    TARGET_ARCH=$${QMAKE_HOST.arch}
}

CONFIG(debug, debug|release) {
        contains(TARGET_ARCH, x86_64) {
            DESTDIR = $$PWD/../../build/Debug
            LIBPATH += $$PWD/../../build/Debug
        } else {
            DESTDIR = $$PWD/../../build/Debug
            LIBPATH += $$PWD/../../build/Debug
        }
        LIBS += -lQNetworkRequestd
} else {
        contains(TARGET_ARCH, x86_64) {
            DESTDIR = $$PWD/../../build/Release
            LIBPATH += $$PWD/../../build/Release
        } else {
            DESTDIR = $$PWD/../../build/Release
            LIBPATH += $$PWD/../../build/Release
        }
        LIBS += -lQNetworkRequest
}

RC_ICONS = resources/networktool.ico

RESOURCES += \
    NetworkRequestTool.qrc

win32 {
    # Copy OpenSSL binary files to build directory
    greaterThan(QT_VERSION, 5.15.0) {
        OPENSSL_FILES = $$PWD/../../ThirdParty/openssl/1.1.1/bin/*.dll
    } else {
        OPENSSL_FILES = $$PWD/../../ThirdParty/openssl/1.0.2/bin/*.dll
    }
    OPENSSL_FILES = $$replace(OPENSSL_FILES, /, \\)
    OUTPUT_FILES_DIR = $$DESTDIR
    OUTPUT_FILES_DIR = $$replace(OUTPUT_FILES_DIR, /, \\)
    QMAKE_POST_LINK += copy /Y $$OPENSSL_FILES $$OUTPUT_FILES_DIR
}
